spring:
  application:
    name: store
  profiles:
    active: dev

# springdoc:
  # swagger-ui:
    # path: /api/v1/docs
  # api-docs:
    # path: /api/v1/api-docs

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 300 # 5 minutes in seconds
  refreshTokenExpiration: 604800 # 7 days in seconds

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}